name: build
on: [push, pull_request]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Use Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Build game
        run: npm run build

      - name: Deploy
        if: github.ref_name == 'master'
        uses: remarkablemark/gitploy-action@v1
        with:
          directory: build
